# Generated by Django 5.0 on 2024-09-14 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0008_alter_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
