# Generated by Django 5.0 on 2024-09-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0010_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='default-username', max_length=100),
            preserve_default=False,
        ),
    ]
